name: Build DLL with MinGW-w64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Windows-Umgebung für MinGW-w64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install MinGW-w64
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            git

      - name: Install 64-Bit Packages
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm base-devel
          pacman -S --noconfirm mingw-w64-x86_64-make
          pacman -S --noconfirm mingw-w64-x86_64-gcc
          pacman -S --noconfirm mingw-w64-x86_64-binutils
          pacman -S --noconfirm mingw-w64-x86_64-toolchain
          pacman -S --noconfirm mingw-w64-x86_64-gdb
          
          gcc --version
          g++ --version
          gdb --version

          git clone https://github.com/asmjit/asmjit.git
          cd asmjit/src/asmjit
          mkdir objs
          cd objs
          rm *.o
          cd ../x86
          g++ -DASMJIT_BUILD_RELEASE -DASMJIT_DYNAMIC -DASMJIT_NO_AARCH64 -DASMJIT_ABI_VERSION=1.13 -I../ -m64 -std=c++20 -O2 -fPIC -shared -c *.cpp
          cp *.o ../objs
          cd ../core
          g++ -DASMJIT_BUILD_RELEASE -DASMJIT_DYNAMIC -DASMJIT_NO_AARCH64 -DASMJIT_ABI_VERSION=1.13 -I../ -m64 -std=c++20 -O2 -fPIC -shared -c *.cpp
          cp *.o ../objs
          cd ../objs
          ar -rcs libasmjit.a *.o
          g++ -DASMJIT_BUILD_RELEASE -DASMJIT_DYNAMIC -DASMJIT_ABI_VERSION=1.13 -I../ -m64 -std=c++20 -O2 -fPIC -shared -o AsmJIT.DLL *.o

      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AsmJIT Library Artefacts
          path: |
            asmjit/src/asmjit/objs/AsmJIT.DLL
            asmjit/src/asmjit/objs/libasmjit.a
